- name: squid 
  hosts: Server
  user: root 
  tasks:
  -  name: configuracíon squid
     ansible.builtin.copy: 
       src: ansibles/docs/Configuracion_squid
       dest: /etc/squid/squid.conf 
  - name: Reiniciar squid 
    ansible.builtin.systemd:
      name: squid 
      state: restarted 
